version: '3.7'

services:
    hugo:
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        container_name: hugo-dev
        volumes:
            - ${PWD}:/src
        ports:
            - 1313:1313
        restart: "on-failure"
        healthcheck:
            test: "${DOCKER_HEALTHCHECK:-wget -q -O /dev/null localhost:1313}"
            interval: "60s"
            timeout: "3s"
            start_period: "5s"
            retries: 3
